import { supabaseAdmin } from "@/server/supabase-admin";
import { sendGmail, ALERT_RECIPIENTS } from "@/server/gmail";
import { uploadReportToDrive } from "@/server/drive";

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

async function buildReport() {
  const since = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString();

  const [visitors, leads, errors, chats] = await Promise.all([
    supabaseAdmin.from("visitor_tracking").select("id, session_id, path, country, created_at").gte("created_at", since),
    supabaseAdmin.from("leads").select("id, name, email, message, source, created_at").gte("created_at", since),
    supabaseAdmin.from("site_errors").select("id, message, path, level, created_at").gte("created_at", since),
    supabaseAdmin.from("chat_logs").select("id, user_message, bot_reply, created_at").gte("created_at", since),
  ]);

  const v = visitors.data ?? [];
  const l = leads.data ?? [];
  const e = errors.data ?? [];
  const c = chats.data ?? [];

  const uniqueSessions = new Set(v.map((x: any) => x.session_id).filter(Boolean)).size;
  const topPaths = Object.entries(
    v.reduce<Record<string, number>>((acc, x: any) => {
      const k = x.path ?? "/";
      acc[k] = (acc[k] ?? 0) + 1;
      return acc;
    }, {}),
  )
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5);

  const html = `
  <div style="font-family:Arial,sans-serif;max-width:680px;margin:0 auto;padding:24px;background:#0a0a0a;color:#fff;border-radius:12px;border:1px solid #FFD700">
    <h1 style="color:#FFD700;margin:0 0 4px">rkInfinity — Weekly Pulse</h1>
    <p style="color:#999;margin:0 0 24px;font-size:13px">${new Date().toUTCString()}</p>

    <div style="display:flex;flex-wrap:wrap;gap:12px;margin-bottom:24px">
      ${kpi("Pageviews", v.length)}
      ${kpi("Unique sessions", uniqueSessions)}
      ${kpi("New leads", l.length)}
      ${kpi("Errors", e.length, "#ef4444")}
      ${kpi("Chat sessions", c.length)}
    </div>

    <h2 style="color:#FFD700;font-size:15px;margin:18px 0 8px">Top pages</h2>
    <table style="width:100%;font-size:13px;border-collapse:collapse">
      ${topPaths.map(([p, n]) => `<tr><td style="padding:4px 0;color:#ccc">${escapeHtml(p)}</td><td style="text-align:right;color:#FFD700">${n}</td></tr>`).join("") || `<tr><td style="color:#666">No traffic</td></tr>`}
    </table>

    <h2 style="color:#FFD700;font-size:15px;margin:24px 0 8px">Recent leads (${l.length})</h2>
    ${l.slice(0, 10).map((x: any) => `
      <div style="padding:10px 0;border-bottom:1px solid #222">
        <div style="font-weight:bold">${escapeHtml(x.name ?? "—")} &lt;${escapeHtml(x.email ?? "")}&gt;</div>
        <div style="color:#aaa;font-size:12px;white-space:pre-wrap;margin-top:4px">${escapeHtml((x.message ?? "").slice(0, 240))}</div>
      </div>
    `).join("") || `<div style="color:#666;font-size:13px">No new leads this week.</div>`}

    <h2 style="color:#ef4444;font-size:15px;margin:24px 0 8px">Errors (${e.length})</h2>
    ${e.slice(0, 10).map((x: any) => `
      <div style="padding:8px 0;border-bottom:1px solid #222;font-size:12px;color:#ddd">
        <div style="color:#ef4444;font-weight:bold">${escapeHtml(x.path ?? "—")}</div>
        <div style="color:#aaa">${escapeHtml((x.message ?? "").slice(0, 200))}</div>
      </div>
    `).join("") || `<div style="color:#666;font-size:13px">No errors logged. 🎉</div>`}

    <p style="color:#666;font-size:11px;margin-top:32px">Auto-generated by rkInfinity Pulse · Backed up to Google Drive · RKInfinity Reports</p>
  </div>
  `;

  return { html, counts: { visitors: v.length, uniqueSessions, leads: l.length, errors: e.length, chats: c.length } };
}

function kpi(label: string, value: number, color = "#FFD700") {
  return `
    <div style="flex:1;min-width:120px;background:#111;border:1px solid #222;border-radius:10px;padding:12px">
      <div style="color:#888;font-size:11px;text-transform:uppercase;letter-spacing:1px">${label}</div>
      <div style="color:${color};font-size:24px;font-weight:bold;margin-top:4px">${value}</div>
    </div>
  `;
}

export async function runWeeklyReport(providedSecret?: string | null) {
  const expected = process.env.WEEKLY_REPORT_SECRET;
  if (expected && providedSecret !== expected) {
    return { status: 401, body: { error: "Unauthorized" } };
  }

  try {
    const { html, counts } = await buildReport();
    const filename = `rkinfinity-weekly-${new Date().toISOString().slice(0, 10)}.html`;

    const emailRes = await sendGmail({
      to: ALERT_RECIPIENTS,
      subject: `📊 rkInfinity Weekly Pulse — ${counts.visitors} views, ${counts.leads} leads`,
      html,
    });

    let drive: { id: string; webViewLink?: string } | null = null;
    let driveError: string | null = null;
    try {
      drive = await uploadReportToDrive({
        filename,
        mimeType: "text/html",
        body: html,
      });
    } catch (e) {
      driveError = e instanceof Error ? e.message : "drive upload failed";
      console.error(driveError);
    }

    return {
      status: 200,
      body: {
        ok: true,
        counts,
        emailed: emailRes.ok,
        emailError: emailRes.error ?? null,
        drive,
        driveError,
      },
    };
  } catch (e) {
    console.error("weekly report failed", e);
    return {
      status: 500,
      body: { error: e instanceof Error ? e.message : "unknown" },
    };
  }
}

export async function handleWeeklyReport(request: Request): Promise<Response> {
  const provided = request.headers.get("x-cron-secret") ?? new URL(request.url).searchParams.get("secret");
  const result = await runWeeklyReport(provided);
  return Response.json(result.body, { status: result.status });
}
