import { Loader2, Download } from "lucide-react";
import jsPDF from "jspdf";

export function Spinner({ label = "Working..." }: { label?: string }) {
  return (
    <div className="flex items-center justify-center gap-2 py-8 text-primary">
      <Loader2 className="animate-spin" size={20} />
      <span className="text-sm">{label}</span>
    </div>
  );
}

export function NeonButton({
  children, onClick, type = "button", disabled, className = "",
}: {
  children: React.ReactNode;
  onClick?: () => void;
  type?: "button" | "submit";
  disabled?: boolean;
  className?: string;
}) {
  return (
    <button
      type={type}
      onClick={onClick}
      disabled={disabled}
      className={`inline-flex items-center justify-center gap-2 rounded-lg bg-gradient-to-r from-primary to-accent px-5 py-2.5 text-sm font-semibold text-primary-foreground hover:opacity-90 transition disabled:opacity-50 disabled:cursor-not-allowed ${className}`}
    >
      {children}
    </button>
  );
}

export function CircularScore({ value, label }: { value: number; label: string }) {
  const r = 42;
  const c = 2 * Math.PI * r;
  const offset = c - (value / 100) * c;
  const color = value >= 90 ? "#22c55e" : value >= 50 ? "#f59e0b" : "#ef4444";
  return (
    <div className="flex flex-col items-center gap-2">
      <div className="relative h-28 w-28">
        <svg className="-rotate-90" viewBox="0 0 100 100">
          <circle cx="50" cy="50" r={r} stroke="currentColor" strokeWidth="8" fill="none" className="text-muted" opacity="0.3" />
          <circle
            cx="50" cy="50" r={r} strokeWidth="8" fill="none"
            stroke={color} strokeDasharray={c} strokeDashoffset={offset} strokeLinecap="round"
            style={{ transition: "stroke-dashoffset 1s ease" }}
          />
        </svg>
        <div className="absolute inset-0 grid place-items-center">
          <span className="text-2xl font-black" style={{ color }}>{value}</span>
        </div>
      </div>
      <div className="text-xs uppercase tracking-wider text-muted-foreground">{label}</div>
    </div>
  );
}

export function downloadPdf(title: string, lines: string[]) {
  const doc = new jsPDF();
  doc.setFontSize(18);
  doc.text(title, 14, 18);
  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text(`Generated by rkInfinity · ${new Date().toLocaleString()}`, 14, 25);
  doc.setTextColor(20);
  doc.setFontSize(11);
  let y = 36;
  for (const line of lines) {
    const wrapped = doc.splitTextToSize(line, 180);
    for (const w of wrapped) {
      if (y > 280) { doc.addPage(); y = 18; }
      doc.text(w, 14, y);
      y += 6;
    }
  }
  doc.save(`${title.toLowerCase().replace(/\s+/g, "-")}.pdf`);
}

export function PdfButton({ onClick }: { onClick: () => void }) {
  return (
    <button
      onClick={onClick}
      className="inline-flex items-center gap-2 rounded-lg glass px-4 py-2 text-xs font-semibold text-primary hover:border-primary/40 transition"
    >
      <Download size={14} /> Download PDF
    </button>
  );
}
