/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as StoryRouteImport } from './routes/story'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiLogErrorRouteImport } from './routes/api/log-error'
import { Route as ApiLeadRouteImport } from './routes/api/lead'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminTrainerRouteImport } from './routes/admin.trainer'
import { Route as ApiPublicWeeklyReportRouteImport } from './routes/api/public/weekly-report'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogErrorRoute = ApiLogErrorRouteImport.update({
  id: '/api/log-error',
  path: '/api/log-error',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadRoute = ApiLeadRouteImport.update({
  id: '/api/lead',
  path: '/api/lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTrainerRoute = AdminTrainerRouteImport.update({
  id: '/trainer',
  path: '/trainer',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicWeeklyReportRoute = ApiPublicWeeklyReportRouteImport.update({
  id: '/api/public/weekly-report',
  path: '/api/public/weekly-report',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/story': typeof StoryRoute
  '/tools': typeof ToolsRoute
  '/admin/trainer': typeof AdminTrainerRoute
  '/api/chat': typeof ApiChatRoute
  '/api/lead': typeof ApiLeadRoute
  '/api/log-error': typeof ApiLogErrorRoute
  '/api/public/weekly-report': typeof ApiPublicWeeklyReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/story': typeof StoryRoute
  '/tools': typeof ToolsRoute
  '/admin/trainer': typeof AdminTrainerRoute
  '/api/chat': typeof ApiChatRoute
  '/api/lead': typeof ApiLeadRoute
  '/api/log-error': typeof ApiLogErrorRoute
  '/api/public/weekly-report': typeof ApiPublicWeeklyReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/story': typeof StoryRoute
  '/tools': typeof ToolsRoute
  '/admin/trainer': typeof AdminTrainerRoute
  '/api/chat': typeof ApiChatRoute
  '/api/lead': typeof ApiLeadRoute
  '/api/log-error': typeof ApiLogErrorRoute
  '/api/public/weekly-report': typeof ApiPublicWeeklyReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/login'
    | '/services'
    | '/story'
    | '/tools'
    | '/admin/trainer'
    | '/api/chat'
    | '/api/lead'
    | '/api/log-error'
    | '/api/public/weekly-report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/login'
    | '/services'
    | '/story'
    | '/tools'
    | '/admin/trainer'
    | '/api/chat'
    | '/api/lead'
    | '/api/log-error'
    | '/api/public/weekly-report'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/login'
    | '/services'
    | '/story'
    | '/tools'
    | '/admin/trainer'
    | '/api/chat'
    | '/api/lead'
    | '/api/log-error'
    | '/api/public/weekly-report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  ServicesRoute: typeof ServicesRoute
  StoryRoute: typeof StoryRoute
  ToolsRoute: typeof ToolsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiLeadRoute: typeof ApiLeadRoute
  ApiLogErrorRoute: typeof ApiLogErrorRoute
  ApiPublicWeeklyReportRoute: typeof ApiPublicWeeklyReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/log-error': {
      id: '/api/log-error'
      path: '/api/log-error'
      fullPath: '/api/log-error'
      preLoaderRoute: typeof ApiLogErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lead': {
      id: '/api/lead'
      path: '/api/lead'
      fullPath: '/api/lead'
      preLoaderRoute: typeof ApiLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trainer': {
      id: '/admin/trainer'
      path: '/trainer'
      fullPath: '/admin/trainer'
      preLoaderRoute: typeof AdminTrainerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/weekly-report': {
      id: '/api/public/weekly-report'
      path: '/api/public/weekly-report'
      fullPath: '/api/public/weekly-report'
      preLoaderRoute: typeof ApiPublicWeeklyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminTrainerRoute: typeof AdminTrainerRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminTrainerRoute: AdminTrainerRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  ServicesRoute: ServicesRoute,
  StoryRoute: StoryRoute,
  ToolsRoute: ToolsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiLeadRoute: ApiLeadRoute,
  ApiLogErrorRoute: ApiLogErrorRoute,
  ApiPublicWeeklyReportRoute: ApiPublicWeeklyReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
